name: release
permissions:
  contents: read
on:
  tags:
    - "v*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.5.0
        with:
          go-version-file: go.mod
      - uses: goreleaser/goreleaser-action@v6.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
